services:
  n8n:
    build:
      context: .
      dockerfile: docker/n8n/Dockerfile
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Tokyo
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - tokium-network

  api:
    build:
      context: .
      dockerfile: docker/node/Dockerfile.dev
    restart: unless-stopped
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      - API_PORT=${API_PORT:-3000}
      - API_KEY=${API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - N8N_URL=http://n8n:5678/webhook/plan-info.v1
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - tokium-network
    depends_on:
      - n8n

volumes:
  n8n_data:

networks:
  tokium-network:
    driver: bridge